spring:
  application:
    name: demo



  datasource:
    url: jdbc:mysql://localhost:3307/demo?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

  jackson:
    deserialization:
      accept-empty-string-as-null-object: true

jwt:
  signKey: "hChCxrv9JExZYhxY0TxLHJhWnQ8Gg6n5zdXe9IEAh6IMYAiZIw9OsSIMh/G/3H/l"

server:
  port: 8081
  servlet:
    context-path: /identity
app:
  service:
    profile: http://localhost:8888/profile

open:
  api:
    title: API document
    version: v1.0.0
    description: API service
    serverUrl: http://localhost:8081
    serverName: server test


springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    urls:
      - name: identity-service
        url: http://localhost:8081/identity/v3/api-docs
      - name: profile-service
        url: http://localhost:8888/profile/v3/api-docs